# Generated by Django 2.2.8 on 2020-03-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200321_1355'),
        ('newsapp', '0003_auto_20200320_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='commented_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='userapp.UserModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='userapp.UserModel'),
            preserve_default=False,
        ),
    ]
