# Generated by Django 2.2.8 on 2020-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20200321_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='header_image',
            field=models.ImageField(default=1, upload_to='post_uploads'),
            preserve_default=False,
        ),
    ]
